# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('flag', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('cook', models.TextField()),
                ('body', markdownx.models.MarkdownxField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Location')),
            ],
        ),
    ]
