# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 04:40
from __future__ import unicode_literals

import cook.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the flag')),
                ('image', models.ImageField(height_field='height', help_text='Image of the flag', upload_to='flags', width_field='width')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the location')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('primary_flag', models.ForeignKey(help_text='Main flag to display for the location', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cook.Flag')),
                ('secondary_flag', models.ForeignKey(blank=True, help_text='Optional second flag to display for the location', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cook.Flag')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used to set the URL - will be based on the title initially', unique=True)),
                ('title', models.TextField(help_text='Displayed as the heading for the recipe')),
                ('date', models.DateField(help_text='Date the recipe was completed. Used for ordering.')),
                ('cook', models.TextField(help_text='Name and description of the cook or cooks')),
                ('body', cook.models.HtmlField(help_text='Body of the recipe, in HTML format.')),
                ('location', models.ForeignKey(help_text='The location that the recipe is associate with', on_delete=django.db.models.deletion.CASCADE, to='cook.Location')),
            ],
        ),
    ]
