# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 08:17
from __future__ import unicode_literals

import common
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=common.HtmlField(help_text='Body of the recipe'),
        ),
    ]
