# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_auto_20160928_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='flag',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='primary_flag',
            field=models.ImageField(default='', height_field='primary_flag_height', upload_to='flags', width_field='primary_flag_width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='primary_flag_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='primary_flag_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='secondary_flag',
            field=models.ImageField(default='', height_field='secondary_flag_height', upload_to='flags', width_field='secondary_flag_width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='secondary_flag_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='secondary_flag_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=markdownx.models.MarkdownxField(help_text='Body of the recipe, in markdown format.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook',
            field=models.TextField(help_text='Name and description of the cook or cooks'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(help_text='Date the recipe was completed. Used for ordering.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='location',
            field=models.ForeignKey(help_text='The location that the recipe is associate with', on_delete=django.db.models.deletion.CASCADE, to='cook.Location'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(help_text='Used to set the URL - will be based on the title initially', unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.TextField(help_text='Displayed as the heading for the recipe'),
        ),
    ]
