# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_auto_20160929_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='secondary_flag',
            field=models.ImageField(blank=True, height_field='secondary_flag_height', upload_to='flags', width_field='secondary_flag_width'),
        ),
        migrations.AlterField(
            model_name='location',
            name='secondary_flag_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='secondary_flag_width',
            field=models.IntegerField(null=True),
        ),
    ]
