# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_auto_20160930_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='secondary_flag_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='secondary_flag_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
