# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0005_auto_20160930_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the flag')),
                ('image', models.ImageField(height_field='height', help_text='Image of the flag', upload_to='flags', width_field='width')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='primary_flag_height',
        ),
        migrations.RemoveField(
            model_name='location',
            name='primary_flag_width',
        ),
        migrations.RemoveField(
            model_name='location',
            name='secondary_flag_height',
        ),
        migrations.RemoveField(
            model_name='location',
            name='secondary_flag_width',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(help_text='Name of the location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='primary_flag',
            field=models.ForeignKey(help_text='Main flag to display for the location', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cook.Flag'),
        ),
        migrations.AlterField(
            model_name='location',
            name='secondary_flag',
            field=models.ForeignKey(blank=True, help_text='Optional second flag to display for the location', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cook.Flag'),
        ),
    ]
