# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 08:14
from __future__ import unicode_literals

import cook.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0007_auto_20161003_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=cook.models.HtmlField(help_text='Body of the recipe, in markdown format.'),
        ),
    ]
