# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 08:18
from __future__ import unicode_literals

import common
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Displayed as the title for the article')),
                ('slug', models.SlugField(help_text='Used to set the URL - will be based on the title initially')),
                ('url', models.URLField(help_text='URL for the section')),
                ('body', common.HtmlField(help_text='Body of the article')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Displayed as the heading for the recipe')),
                ('slug', models.SlugField(help_text='Used to set the URL - will be based on the title initially')),
                ('url', models.URLField(help_text='URL for the section')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent section, if there is one', null=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.Section')),
            ],
        ),
    ]
