# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 08:12
from __future__ import unicode_literals

import common
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Displayed as the title for the article')),
                ('slug', models.SlugField(help_text='Used to set the URL - will be based on the title initially')),
                ('body', common.HtmlField(help_text='Body of the article')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Displayed as the heading for the recipe')),
                ('slug', models.SlugField(help_text='Used to set the URL - will be based on the title initially')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(help_text='Parent section, if there is one', null=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.Section')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(help_text='Section containing this article', on_delete=django.db.models.deletion.CASCADE, to='navigation.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('slug', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('slug', 'section')]),
        ),
    ]
