# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 08:12
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Section = apps.get_model("navigation", "Section")
    db_alias = schema_editor.connection.alias

    Section.objects.using(db_alias).create(
        title="root", slug="", lft=1, rght=2, tree_id=1, level=0
    )


def reverse_func(apps, schema_editor):
    Section = apps.get_model("navigation", "Section")
    db_alias = schema_editor.connection.alias
    Section.objects.using(db_alias).filter(slug="", parent=None).delete()


class Migration(migrations.Migration):

    dependencies = [('navigation', '0001_initial'), ]

    operations = [migrations.RunPython(forwards_func, reverse_func), ]
